apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: infra
  labels:
    app: kafka-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:v0.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /kafka-ui
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-0.kafka-headless.infra.svc.cluster.local:9093,kafka-1.kafka-headless.infra.svc.cluster.local:9093,kafka-2.kafka-headless.infra.svc.cluster.local:9093
            - name: KAFKA_CLUSTERS_0_ZOOKEEPER
              value: kafka-zookeeper:2181
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-ui
