apiVersion: v1
kind: Service
metadata:
  name: logging-winston
  namespace: backend
spec:
  selector:
    app: logging-winston
  ports:
    - name: api
      port: 3300
      targetPort: 3300
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logging-winston
  namespace: backend
spec:
  hosts:
    - "api.backend.com"
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /logging-winston/
      rewrite:
        uri: /
      route:
        - destination:
            host: logging-winston
            port:
              number: 3300
