apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: backend
spec:
  selector:
    app: kafka-producer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka-producer
  namespace: backend
spec:
  hosts:
    - "api.backend.com"
  gateways:
    - istio-system/gateway
  http:
    - match:
        - uri:
            prefix: /kafka-producer/
      rewrite:
        uri: /
      route:
        - destination:
            host: kafka-producer
            port:
              number: 3000
