apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: infra
data:
  fluentd.conf: |
    <source>
      @type http
      port 9880
    </source>
    <source>
      @type forward
      port 24224
    </source>
    <match *.**>
      @type copy
      <store>
        @type stdout
      </store>
    </match>
