apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
spec:
  profile: default
  values:
    global:
      istioNamespace: istio-system
      proxy:
        resources:
          limits:
            cpu: 250m      #  In Istio 1.15.2, a proxy consumes about 0.5 vCPU per 1000 requests per second.
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi

    gateways:
      istio-ingressgateway:
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi

    pilot:
      resources:
        requests:
          memory: 1024Mi

  meshConfig:
    enableTracing: true
    defaultConfig:
      tracing:
        sampling: 50.0
        zipkin:
          address: jaeger-collector.infra:9411
