version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.4
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always
    networks:
      - messagequeue

  kafka:
    image: confluentinc/cp-kafka:6.1.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:29092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always
    networks:
      - messagequeue

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    hostname: kafka-ui
    ports:
      - "9021:8080"
    depends_on:
      - zookeeper
      - kafka
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - messagequeue

networks:
  messagequeue:
    name: messagequeue
    driver: bridge
